### ISSUE TITLE
Standard / Reference for this repo

### ISSUE THREAD

**Issue by WERDXZ** [alfg/mp4-rust#133]
Hey everyone!

I'm currently working on adding a [Timed Metadata Track](https://developer.apple.com/documentation/quicktime-file-format/timed_metadata_media) feature to this project and have been referring to the [Apple QTFF documentation](https://developer.apple.com/documentation/quicktime-file-format). However, I've noticed some inconsistencies (e.g. between the [Apple Doc](https://developer.apple.com/documentation/quicktime-file-format/video_media_information_atom) and `MinfBox` implementation in crate) between this document and the current state of the repo.

I saw in the README that the project references the ISO standards (that links to Wikipedia, which doesn't provide much useful information), which are often behind a paywall and thus not readily accessible for reference. Could you please provide some information about documents or resources that were referenced while developing this repo? It will be very helpful for aligning my work with this project.:)

Regards,
WERDXZ

PS: I'm using this repo for the QuickTime MOV part of creating Apple's Live Photo in rust, and here is a [reference](https://stackoverflow.com/questions/32508375/apple-live-photo-file-format/35286486#35286486) for it.

**Comment by alfg** [comment]
Unfortunately, the ISO standards are behind a paywall, so I can't link or upload them here directly. But if you search around on Google, you can find them easily.

**Comment by WERDXZ** [comment]
Thank you very much
