### ISSUE TITLE
Help wanted, how could I encode mp4 file with array of `RGB24` pixels

### ISSUE THREAD

**Issue by Brooooooklyn** [alfg/mp4-rust#33]

**Comment by alfg** [comment]
Hi @Brooooooklyn, 

`mp4-rust` does not encode or decode video as it has no codec. It only reads and writes the byte structure of an MP4 file. You can probably use something like ffmpeg's libav to encode RGB24 to a compressed format.

**Comment by alfg** [comment]
Closing. Feel free to respond if any more questions. Thanks!
