### ISSUE TITLE
Error in mp4sample example

### ISSUE THREAD

**Issue by miluxmilux** [alfg/mp4-rust#35]
Hi there,
I think the mp4sample is a little out-of-date. 
The expected input as printed is `./mp4sample <track_id> <filename>`. In reality, the example only uses the filename, and expects it at args[1], not args[2].

```
-        println!("Usage: mp4sample <track_id> <filename>");
+        println!("Usage: mp4sample <filename>");
```

Really useful crate, thanks!

**Comment by alfg** [comment]
Good catch @miluxmilux! I've updated the example to just `println!("Usage: mp4sample <filename>");`. 

Thank you!
