### ISSUE TITLE
Writing is_sync doesn't work properly

### ISSUE THREAD

**Issue by Jos635** [alfg/mp4-rust#38]
Hi! I'm trying to generate a video from a set of static images with this library and the x264 library. I noticed that no matter what I set `is_sync` in `Mp4Sample` to, all frames are always end up having `is_sync: true`.

I think it might be related to the implementation [here](https://github.com/alfg/mp4-rust/blob/master/src/track.rs#L664). If I change the code to this:

    fn update_sync_samples(&mut self, is_sync: bool) {
        if let Some(ref mut stss) = self.trak.mdia.minf.stbl.stss {
            if !is_sync {
                return;
            }

            stss.entries.push(self.sample_id);
        } else {
            let mut stss = StssBox::default();
            for i in 1..=self.trak.mdia.minf.stbl.stsz.sample_count {
                stss.entries.push(i);
            }
            self.trak.mdia.minf.stbl.stss = Some(stss);
        };
    }

The `is_sync` value is written properly. I'm not quite sure what the code is supposed to be doing, so I'm not sure if this breaks other cases.

To reproduce the issue, you can use the `mp4copy` example to copy an mp4 file, and then use the `mp4sample` example to observe that all video frames are suddenly sync.

**Comment by alfg** [comment]
Thanks @Jos635. I'll check into this.

**Comment by alfg** [comment]
Hey @Jos635, 

Thanks for catching this. I've added a fix (and fixed another issue in this same method). I confirmed by running `mp4copy` and `mp4sample` to compare.

I've published the package as `mp4 = "0.7.2"` if you can give it a try and close the issue if resolved.

Thanks!

**Comment by Jos635** [comment]
Hi, thanks for fixing it so quickly! I can confirm that `0.7.2` works properly.
