### ISSUE TITLE
Add video encoding example.

### ISSUE THREAD

**Issue by pudnax** [alfg/mp4-rust#40]
I don't know exactly how to fill in the fields of the structures. It would be good to know the basic combination of version, SPS, PPS which works in most cases. And what the `Bytes` should look like, raw bytes of frame in the R8G8B8A8 format i hope.

**Comment by alfg** [comment]
Hey @pudnax, 

I don't have an encoding example, but have you checked out the [mp4copy](https://github.com/alfg/mp4-rust/blob/master/examples/mp4copy.rs) example? If you have the sps/pps and sample data, you can write it in the TrackConfig and sample writer.

**Comment by alfg** [comment]
Closing. Feel free to respond if any other questions. Thanks!
