### ISSUE TITLE
`BoxNotFound(moov)` error in `mp4::Mp4Reader::read_header`

### ISSUE THREAD

**Issue by probablykasper** [alfg/mp4-rust#48]
`.m4a` files saved by QuickTime Player result in a `BoxNotFound(moov)` error when running `mp4::Mp4Reader::read_header`.

The file can be played in QuickTime Player, Chrome and VLC just fine.

The `moov` doesn't seem to be missing:
![image](https://user-images.githubusercontent.com/11315492/106375794-9e2aa480-638f-11eb-88b5-a625814c1302.png)

And output from `ffprobe` seems ok:
```
  Metadata:
    major_brand     : M4A
    minor_version   : 0
    compatible_brands: M4A mp42isom
    creation_time   : 2021-01-31T05:24:23.000000Z
    iTunSMPB        :  00000000 00000840 00000240 00000000007CA580 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
  Duration: 00:03:05.23, start: 0.047891, bitrate: 127 kb/s
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 126 kb/s (default)
    Metadata:
      creation_time   : 2021-01-31T05:24:23.000000Z
      handler_name    : Core Media Audio
```

Here's the m4a file:

https://user-images.githubusercontent.com/11315492/106375747-5441be80-638f-11eb-84fe-80629af044de.mp4

**Comment by probablykasper** [comment]
Wait a minute, it is actually missing in the screenshot I took, my bad. But, it does still plays fine and such.

Looks like the `moov` is near the bottom of the file:
![image](https://user-images.githubusercontent.com/11315492/106376170-e8615500-6392-11eb-8687-19eb5a7dc25c.png)

**Comment by alfg** [comment]
Good find. I think it's a bug when parsing a largesize mdat. I'll check it out.

**Comment by alfg** [comment]
@probablykasper Can you try the branch in the PR? #49

**Comment by probablykasper** [comment]
@alfg Sure, but will have to do it tomorrow

**Comment by alfg** [comment]
@probablykasper No worries. Thanks for finding this. Have a good night.

**Comment by probablykasper** [comment]
@alfg Works like a charm! And thanks for also adding `Freq7350`

**Comment by alfg** [comment]
@probablykasper Great! It's merged. I'll be bumping the `mp4` crate version later today.

**Comment by alfg** [comment]
Also, this helped me fix the issue I was having with qt files on https://alfg.github.io/mp4-inspector/ 😄

**Comment by probablykasper** [comment]
@alfg Oh shit, found that website while debugging, had no idea it was made by you. Nice!
