### ISSUE TITLE
Support more audio object formats

### ISSUE THREAD

**Issue by probablykasper** [alfg/mp4-rust#51]
Currently, these are the only audio object formats `mp4-rust` supports:
```
AacMain
AacLowComplexity
AacScalableSampleRate
AacLongTermPrediction
```

The MPEG-4 Wikipedia article lists [46 audio object types](https://en.wikipedia.org/wiki/MPEG-4_Part_3#MPEG-4_Audio_Object_Types). Would be great to support all of them

**Comment by compenguy** [comment]
Just piping up to say that I filed the issue against redlux - I think the highest impact missing object types are probably SBR and PS, although I think only the lack of SBR is affecting me right now.

**Comment by alfg** [comment]
Hey, thanks for reporting this. I'll look into adding in more audio object types soon.

**Comment by alfg** [comment]
@probablykasper @compenguy 

Created #52 to add more audio object types, including SBR and PS. 

Let me know if this looks good and I'll merge and create a release later in the day.

**Comment by probablykasper** [comment]
Looks great, thank you! :D

**Comment by alfg** [comment]
Thanks for checking!

Merged and published as `0.8.2`.
https://crates.io/crates/mp4/0.8.2

**Comment by compenguy** [comment]
Super awesome, just tested 0.8.2 from my patched branch of redlux - everything works great!

**Comment by alfg** [comment]
@compenguy Awesome. Thanks for reporting back.

@probablykasper Can this be closed?

**Comment by probablykasper** [comment]
Yep, thanks
