### ISSUE TITLE
Bad box header causing read_header dead-looping.

### ISSUE THREAD

**Issue by qianzhang5** [alfg/mp4-rust#64]
I have a surveillance footage that has a size zero BoxHeader, which causes dead-looping in reader.rs line 30 "while current < size ..."
suggest: 
    while current < size {
            // Get box header.
            let header = BoxHeader::read(&mut reader)?;
            let BoxHeader { name, size: s } = header;
            if s == 0 {
                break;
            }

**Comment by alfg** [comment]
Hey @qianzhang5. Good catch. I'll take a look soon and add the suggested fix. PRs are also welcome. :)

If you can provide a sample file with the bad box header to test/validate, that would be great as well.

**Comment by qianzhang5** [comment]
how do I upload the video clip for you?

**Comment by alfg** [comment]
how big is the file? Can it be attached here via drag and drop?

**Comment by qianzhang5** [comment]
test.mp4
<https://drive.google.com/file/d/16YA7Gecj3s1qfE15lu2kUU6WQkZecfMg/view?usp=drive_web>

**Comment by qianzhang5** [comment]
Let me know after you download. I will remove the link of the driver.
Thanks!

**Comment by alfg** [comment]
Is there a public link I can download from? It says access denied. If it's small enough, you can just attach it here.

**Comment by qianzhang5** [comment]
Sorry, my mistake.
here is a link  you can download http://qianzhang.linkpc.net/files/test.mp4

**Comment by alfg** [comment]
Thanks for the sample. I've confirmed the issue and your suggested fix. I'll run a few tests and merge/publish soon.

Thanks for catching this @qianzhang5!

**Comment by qianzhang5** [comment]
Great, thanks!

**Comment by alfg** [comment]
Hi @qianzhang5, https://crates.io/crates/mp4/0.9.2 is deployed with the fix. Thanks again.
