### ISSUE TITLE
AvcConfig Usage

### ISSUE THREAD

**Issue by EVLRBT-01** [alfg/mp4-rust#74]
Hi there!

I am trying to combine a .png image and .m4a audio file and am not sure what is required for `pic_param_set`/`seq_param_set`. Could you possibly provide a pointer please?

PS - I assume the image/audio data is added to the resulting mp4 via the `mp4_writer.write_sample` function?

Thanks!

**Comment by alfg** [comment]
Hey @EVLRBT-01, check out the `mp4copy` example for an idea of setting the sps/pps in AvcConfig by using the bytes extracted from the track data.

**Comment by alfg** [comment]
Closing. Feel free to respond with any questions.
