### ISSUE TITLE
How to convert PNG images to mp4?

### ISSUE THREAD

**Issue by womeng2009** [alfg/mp4-rust#79]
I looked at the mp4copy.rs example, but I don't understand how to convert a collection of PNG images to an mp4 file. please help me!

**Comment by alfg** [comment]
Hey @womeng2009, you might be better off using something like ffmpeg to convert PNG images to an MP4. This library is used for reading and writing MP4 boxes, which already have an encoded stream.

**Comment by womeng2009** [comment]
> Hey @womeng2009, you might be better off using something like ffmpeg to convert PNG images to an MP4. This library is used for reading and writing MP4 boxes, which already have an encoded stream.

Thank you.
