### ISSUE TITLE
Private API

### ISSUE THREAD

**Issue by TroyKomodo** [alfg/mp4-rust#83]
Hi, I was curious why pretty much all of the boxes are private. It makes this library annoying to use when writing a remuxer into MP4 or (FMP4).
I am trying to take a raw FLV stream and generate fragmented MP4 segments, basically i want to construct the boxes and use this library to serialize them into binary. However this library makes that impossible due to the private modifiers on all the mp4 boxes.

Wondering if this was intentional or if it was just an oversight.

Your library is great btw and I would love to use it!

**Comment by alfg** [comment]
Hi, yes it is intended to be used more of a high-level mp4 reader/writer.

**Comment by TroyKomodo** [comment]
I understand that but why?
Why not provide high level access and then also provide lower level access?
The cost of doing so is nothing and it only adds features and does not retract from the library in anyway.
