### ISSUE TITLE
Getting frames from video

### ISSUE THREAD

**Issue by kenseii** [alfg/mp4-rust#85]
Hello,

Is it possible to get frames/images from an `MP4Reader`?
Thank you

**Comment by alfg** [comment]
You can read the sample bytes using `mp4.read_sample`, but you will need a decoder if you're looking to decode the actual frames. This project does not do any encoding/decoding, just mp4 box reading/writing.

Check out [mp4sample.rs](https://github.com/alfg/mp4-rust/blob/master/examples/mp4sample.rs) for an example of reading track samples.
