### ISSUE TITLE
Does it support combine openexr images to video?

### ISSUE THREAD

**Issue by jinfagang** [alfg/mp4-rust#92]
hello, may I ask does it support combines openexr images to video? I think normal jpg is supported

**Comment by alfg** [comment]
No, this library doesn't support encoding/decoding media, only box construction for the mp4 container.

**Comment by jinfagang** [comment]
@alfg  thanks. Can u guide me a workable lib if I want merge jpg or other image format into mp4 in rust?

**Comment by alfg** [comment]
Unfortunately not. FFmpeg or libav may work, but not familiar with a rust library.
